### ISSUE TITLE
show_weights: Tried to call get_weights_view on a dataset that has no view converter

### ISSUE THREAD

**Issue by denadai2** [lisa-lab/pylearn2#1094]
I'm using this yaml file

```
!obj:pylearn2.train.Train {
dataset: &train !obj:pylearn2.datasets.csv_dataset.CSVDataset {
    path: 'train.csv'
},
model: !obj:pylearn2.models.mlp.MLP {
    layers: [
             !obj:pylearn2.models.mlp.Sigmoid {
                 layer_name: 'h0',
                 dim: 300,
                 sparse_init: 15
             },
             !obj:pylearn2.models.mlp.Linear {
                 layer_name: 'y',
                 irange: 0.5,
                 dim: 1
             }
            ],
    nvis: 20,
},
algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
    batch_size: 10,
    learning_rate: .001,
    monitoring_dataset:
        {
            'train' : *train,
            'test'  : !obj:pylearn2.datasets.csv_dataset.CSVDataset {
                            path: 'testY.csv'
                        },
        },
    termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
        max_epochs: 10
    },
},
extensions: [
    !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
        channel_name: "train_objective",
        save_path: "best.pkl"
    }
],
save_path: "softmax_regression.pkl",
save_freq: 1
}
```

and I used this command:

```
show_weights.py best.pkl
```

I received this error:

 Traceback (most recent call last):
  File "../../pylearn2/pylearn2/scripts/show_weights.py", line 52, in <module>
    show_weights(args.path, args.rescale, args.border, args.out)
  File "../../pylearn2/pylearn2/scripts/show_weights.py", line 28, in show_weights
    border=border)
  File "/Users/denadai2/Documents/pylearn2/pylearn2/gui/get_weights_report.py", line 145, in get_weights_report
    weights_view = dataset.get_weights_view(W)
  File "/Users/denadai2/Documents/pylearn2/pylearn2/datasets/dense_design_matrix.py", line 779, in get_weights_view
    raise Exception("Tried to call get_weights_view on a dataset "
Exception: Tried to call get_weights_view on a dataset that has no view converter

**Comment by SinaResearch** [comment]
I have the same problem here. Could you find any solution?
