### ISSUE TITLE
test_softmax_binary_targets occasionally fails if run on gpu

### ISSUE THREAD

**Issue by JesseLivezey** [lisa-lab/pylearn2#1380]
Test occasionally fails when run on gpu, but doesn't seem to fail when run on cpu. Seems to be a tolerance problem.
```
======================================================================
FAIL: Constructs softmax layers with binary target and with vector targets
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jesse/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/jesse/Development/pylearn2/pylearn2/models/tests/test_mlp.py", line 661, in test_softmax_binary_targets
    cost_vec(X_data, y_vec_data))
  File "/home/jesse/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 1297, in assert_allclose
    verbose=verbose, header=header)
  File "/home/jesse/anaconda/lib/python2.7/site-packages/numpy/testing/utils.py", line 665, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 100.0%)
 x: array(2.313629150390625, dtype=float32)
 y: array(2.313629388809204, dtype=float32)

----------------------------------------------------------------------
```

**Comment by lamblin** [comment]
The tolerance seems really low for float32, I think it should be increased.
