### ISSUE TITLE
MNIST maxout example crashes

### ISSUE THREAD

**Issue by Pastafarianist** [lisa-lab/pylearn2#1391]
I am trying to reproduce the result stated [here](https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/scripts/papers/maxout/README), namely, 0.45% on MNIST. I am running pylearn2 on Amazon EC2 from [this image](http://thecloudmarket.com/image/ami-39296709--caffe-theano-pylearn2-torch7-cuda6-5-ubuntu14-04-gpu). I set up a g2.2xlarge instance, booted up and ran:

    sudo -s
    cd pylearn2/pylearn2/scripts/papers/maxout/
    THEANO_FLAGS="device=gpu,floatX=float32" ~/pylearn2/pylearn2/scripts/train.py mnist.yaml

pylearn2 crashed with the following traceback ([a more complete gist](https://gist.github.com/Pastafarianist/9ccfb0dd10660eabc055)):

    root@ip-172-31-44-36:~/pylearn2/pylearn2/scripts/papers/maxout# THEANO_FLAGS="device=gpu,floatX=float32" ~/pylearn2/pylearn2/scripts/train.py mnist.yaml
    Using gpu device 0: GRID K520
    error: XDG_RUNTIME_DIR not set in the environment.
    error: XDG_RUNTIME_DIR not set in the environment.
     
    (train.py:5031): Gdk-CRITICAL **: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
    Traceback (most recent call last):
      File "/home/ubuntu/pylearn2/pylearn2/scripts/train.py", line 252, in <module>
        args.verbose_logging, args.debug)
      File "/home/ubuntu/pylearn2/pylearn2/scripts/train.py", line 197, in train
        train_obj = serial.load_train_file(config)
      File "/home/ubuntu/pylearn2/pylearn2/utils/serial.py", line 524, in load_train_file
        return yaml_parse.load_path(config_file_path, environ=environ)
      File "/home/ubuntu/pylearn2/pylearn2/config/yaml_parse.py", line 379, in load_path
        return load(content, instantiate=instantiate, environ=environ, **kwargs)
      File "/home/ubuntu/pylearn2/pylearn2/config/yaml_parse.py", line 335, in load
        proxy_graph = yaml.load(string, **kwargs)
      File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
        return loader.get_single_data()
      File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 39, in get_single_data
        return self.construct_document(node)
      File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 43, in construct_document
        data = self.construct_object(node)
      File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 90, in construct_object
        data = constructor(self, tag_suffix, node)
      File "/home/ubuntu/pylearn2/pylearn2/config/yaml_parse.py", line 479, in multi_constructor_obj
        mapping = loader.construct_mapping(node)
      File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 208, in construct_mapping
        return BaseConstructor.construct_mapping(self, node, deep=deep)
      File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 133, in construct_mapping
        value = self.construct_object(value_node, deep=deep)
      File "/usr/lib/python2.7/dist-packages/yaml/constructor.py", line 90, in construct_object
        data = constructor(self, tag_suffix, node)
      File "/home/ubuntu/pylearn2/pylearn2/config/yaml_parse.py", line 493, in multi_constructor_obj
        callable = try_to_import(tag_suffix)
      File "/home/ubuntu/pylearn2/pylearn2/config/yaml_parse.py", line 391, in try_to_import
        exec('import %s' % modulename)
      File "<string>", line 1, in <module>
      File "/home/ubuntu/pylearn2/pylearn2/models/mlp.py", line 26, in <module>
        from pylearn2.linear import conv2d
      File "/home/ubuntu/pylearn2/pylearn2/linear/conv2d.py", line 20, in <module>
        from pylearn2.packaged_dependencies.theano_linear.conv2d \
      File "/home/ubuntu/pylearn2/pylearn2/packaged_dependencies/theano_linear/__init__.py", line 9, in <module>
        from conv2d import Conv2d
      File "/home/ubuntu/pylearn2/pylearn2/packaged_dependencies/theano_linear/conv2d.py", line 3, in <module>
        from .imaging import tile_slices_to_image, most_square_shape
      File "/home/ubuntu/pylearn2/pylearn2/packaged_dependencies/theano_linear/imaging.py", line 9, in <module>
        from pylearn2.utils.image import Image, ensure_Image
      File "/home/ubuntu/pylearn2/pylearn2/utils/image.py", line 12, in <module>
        import matplotlib.pyplot as plt
      File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 109, in <module>
        _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
      File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
        globals(),locals(),[backend_name],0)
      File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 11, in <module>
        from . import backend_gtk3
      File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3.py", line 55, in <module>
        cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
    TypeError: constructor returned NULL

**Comment by dwf** [comment]
Why on earth are you running with sudo?

Seems like you have a problem with your matplotlib install, but it's
unclear to me why matplotlib should need to be imported, so I'll leave this
issue open for the time being.

**Comment by Pastafarianist** [comment]
I need sudo because otherwise Theano fails to write a temporary file during some compilation.

**Comment by lamblin** [comment]
Maybe specify a different base directory for compilation, by setting the `base_compiledir` flag.

**Comment by Pastafarianist** [comment]
@lamblin I would guess that TypeError should be handled in https://github.com/lisa-lab/pylearn2/blob/master/pylearn2/utils/image.py#L13. I have created a relevant pull request at https://github.com/lisa-lab/pylearn2/pull/1395

**Comment by lamblin** [comment]
Fixed by gh-1395.

**Comment by Pastafarianist** [comment]
Unfortunately, this issue has to be reopened.

First, there's another place where matplotlib is imported in this example. It's in `/pylearn2/pylearn2/packaged_dependencies/theano_linear/unshared_conv/localdot.py`. The same fix applies (although this file handles the import failure a bit differently).

Second, even after `localdot.py` is patched, `cuda_convnet` compilation crashes with [this output](https://gist.github.com/Pastafarianist/d40c3bf369b73ae91ac0). I have no idea how to make any sense of it.

**Comment by lamblin** [comment]
Regarding the crash, this is due to your Theano version being too old, and out of sync with Pylearn2.
In particular, your Theano version links with cublas via the legacy API, whereas the version of cuda-convnet packaged with pylearn2 uses the new API, cublas_v2.
You should use the bleeding-edge install of Theano.
