### ISSUE TITLE
Pylearn2 IOError: Permission denied 

### ISSUE THREAD

**Issue by janarbek** [lisa-lab/pylearn2#1577]
Hi All,

I am using trying to run BinaryNet which uses PyLearn2.  When I am running the mnist.py of BinaryNet, it is giving me PyLeran2 related error as follows. I am on Windows 7 machine and I am the admin of this machine. I am wondering if anyone has suggestions ?

Thanks in advance for your help.

Using gpu device 0: Quadro K620 (CNMeM is disabled, cuDNN not available)
C:\Users\jmatai\AppData\Local\Continuum\Anaconda2\lib\site-packages\theano\tensor\signal\downsample.py:6: UserWarning: downsample module has been moved to the t
heano.tensor.signal.pool module.
"downsample module has been moved to the theano.tensor.signal.pool module.")
batch_size = 100
alpha = 0.1
epsilon = 0.0001
num_units = 4096
n_hidden_layers = 3
num_epochs = 1000
dropout_in = 0.2
dropout_hidden = 0.5
activation = binary_net.binary_tanh_unit
binary = True
stochastic = False
H = 1.0
W_LR_scale = Glorot
LR_start = 0.003
LR_fin = 3e-07
LR_decay = 0.990831944893
save_path = mnist_parameters.npz
shuffle_parts = 1
Loading MNIST dataset...
Traceback (most recent call last):
File "mnist.py", line 93, in 
train_set = MNIST(which_set= 'train', start=0, stop = 50000, center = False)
File "c:\projects\python_packages\pylearn2\pylearn2\datasets\mnist.py", line 93, in init
topo_view = read_mnist_images(im_path, dtype='float32')
File "c:\projects\python_packages\pylearn2\pylearn2\utils\mnist_ubyte.py", line 94, in read_mnist_images
with open_if_filename(fn, 'rb') as f:
File "c:\projects\python_packages\pylearn2\pylearn2\utils\mnist_ubyte.py", line 46, in enter
self._handle = open(self._f, self._mode, self._buffering)
IOError: [Errno 13] Permission denied: 'C:\projects\repos\dl\data/mnist/train-images-idx3-ubyte'

**Comment by nouiz** [comment]
The error is:


IOError: [Errno 13] Permission denied: 'C:\projects\repos\dl\data/
mnist/train-images-idx3-ubyte'

You probably don't have that file or it don't have good permission.

note Pylearn2 isn't supported anymore.

**Comment by janarbek** [comment]
Thank you Nouiz,

Yes, that is what I thought. But I am admin of this machine, and I do have the files. For example, if I moved the files somewhere else intentionally, then I will get "No file exist" error. That means I do have the files. 

However, I am not sure why I am getting Permission denied error.

Unfortunately, I have to use pylearn2 because I am trying to run BinaryNet which uses Pylearn2.
